Example of object creation attribute shortcut
jqlang/jq pull request #1454
Opened 2017-07-21 14:06 UTC by sloanlance

A suggestion for the tutorial:

Use an attribute name without a value in the object creation to give an example of the shortcut syntax.

2017-07-21 14:24 UTC, sloanlance commented
Tell me if I need to do anything about the Travis CI failure.

2023-06-07 12:11 UTC, itchyny requested changes

2023-06-07 12:11 UTC, itchyny commented on docs/content/1.tutorial/default.yml
> +        "sha": d25341478381063d1c76e81b3a52e0592a7c997f
This is not a valid result JSON.

2023-06-09 11:31 UTC, itchyny commented
The tutorial explains very basic concepts for beginners, and adding a shortcut syntax to this page is not appropriate in my opinion. Closing the PR, but thank you.

2023-06-09 11:31 UTC, closed without merging