Update manual.yml
jqlang/jq pull request #1537
Opened 2017-11-23 13:41 UTC by yonatan-py

I think there was a small mistake :)

2017-11-23 16:25 UTC, pkoppstein requested changes
The update is partly wrong. The .x in the update should be x, as in the original.

2017-11-24 18:00 UTC, yonatan-py commented
@pkoppstein just tried my example again, they seem to be valid.
:dango:

2017-11-24 18:07 UTC, pkoppstein commented
I am referring to the sentence: map(x)` is equivalent to `[.[] | .x]`

It doesn't matter what you tried, the above is absolutely incorrect.  As should be self evident, it should read:

     `map(x)` is equivalent to `[.[] | x]`

2018-09-05 20:59 UTC, EugenGez commented
`map(x) is defined as [.[] | x]`

The `x` is a placeholder...

2023-06-04 08:03 UTC, itchyny commented
Yes, as commented above, the manual is correct.

2023-06-04 08:03 UTC, closed without merging