add nested array indexing example
jqlang/jq pull request #1849
Opened 2019-02-26 22:06 UTC by kevpl

This PR adds an example to the docs to help people who've hit the snag
discussed in #1168.

Having an example allows people who hit this snag to relatively quickly
see what they've done wrong, rather than having to probe further into a
cryptic error message:
```
jq: error: syntax error, unexpected $end, expecting FORMAT or QQSTRING_START (Unix shell quoting issues?)
```

Having it just as an example allows people to be informed of the behavior
without the burden of needing to explain it with additional text.

2019-02-27 04:03 UTC, nicowilliams commented
I mean, the manual is littered with examples like this, but I guess the point is that just the section on array indexing can confuse people, so I'll take it.

2019-12-30 11:13 UTC, Alanscut approved these changes

2019-12-30 17:09 UTC, nicowilliams commented on docs/content/manual/manual.yml
> +            output: '"b"'
This needs to be `output: ['"b"']`.

2023-06-07 12:32 UTC, itchyny requested changes
The example output needs to be corrected as commented before.

2026-09-18 14:36 UTC, closed without merging