Document use of length on numbers
jqlang/jq pull request #2625
Opened 2023-06-20 07:07 UTC by alexjurkiewicz

This was added in ae7a042876130c471dce28a4396abc215192eaa9 but not explicitly documented.

2023-06-20 07:33 UTC, wader approved these changes

2023-06-20 07:35 UTC, wader commented
As we're nearly listing all types, should we also add that length of boolean is an error?

2023-06-20 08:16 UTC, wader approved these changes
Maybe update PR title?

2023-06-20 09:06 UTC, itchyny requested changes
This needs to applied to the development version manual too. Also, the period is missing (sorry for nitpick).

2023-06-21 08:18 UTC, wader approved these changes
@itchyny do we care to update < 1.6 verisons too?

2023-06-21 09:20 UTC, itchyny approved these changes
LGTM, thank you.

@wader
Document improvements are good enough if been applied to the latest released & development versions. But talking of typo fixes, they keep sending patches with spell checkers even if it is in older version manuals, so I'd like to fix them all.

2023-06-21 09:21 UTC, merged