Make field colors configurable
jqlang/jq pull request #2638
Opened 2023-06-28 23:01 UTC by ericpruitt

Allow object key colors to be configured with the "JQ_COLORS" environment variable. This is a updated version of a [GitHub pull request created by David
Haguenauer](https://github.com/stedolan/jq/pull/1791). Since the prebuilt manual already needed to be updated, this change also fixes in omission in <https://github.com/stedolan/jq/commit/cf61515> in which "39" in "JQ_COLORS" should have been replaced with "37".

2023-06-28 23:22 UTC, ericpruitt commented
I also wrote a script called jqcolors that's analagous to dircolors that I could include in a separate PR if you'd accept it: <https://github.com/ericpruitt/emus/blob/master/scripts/jqcolors>.

Example file:
```
~$ cat .jqcolors
STRING  0           # Default
ARRAY   0           # Default
OBJECT  0           # Default
FIELD   1;37        # Bold White

# XTerm colors are used for these tokens to make the text bright -- having the
# red, green and/or blue channels maxed out -- without being bold.
NULL    0;38;5;226  # Yellow
FALSE   0;38;5;196  # Red
TRUE    0;38;5;46   # Green
NUMBER  0;38;5;201  # Magenta
```

2023-06-29 13:51 UTC, itchyny requested changes

2023-06-29 13:51 UTC, itchyny commented on tests/shtest
>  $JQ -Ccn . > $d/color
Please prepend `JQ_COLORS= ` this line and L307. `make check` fails when exporting the environment variable.

2023-06-29 13:51 UTC, itchyny commented on src/jv.h
> +  JV_KIND_FIELD
Please see https://github.com/jqlang/jq/pull/1791#issuecomment-1613218512.

2023-07-18 22:53 UTC, closed without merging